using MemoryPack;

namespace CryBits.Protocol.Packets.Client;

[MemoryPackable]
[MemoryPackUnion(0, typeof(ConnectPacket))]
[MemoryPackUnion(1, typeof(RegisterPacket))]
[MemoryPackUnion(2, typeof(CreateCharacterPacket))]
[MemoryPackUnion(3, typeof(CharacterUsePacket))]
[MemoryPackUnion(4, typeof(CharacterCreatePacket))]
[MemoryPackUnion(5, typeof(CharacterDeletePacket))]
[MemoryPackUnion(6, typeof(MessagePacket))]
[MemoryPackUnion(7, typeof(WriteClassesPacket))]
[MemoryPackUnion(8, typeof(WriteMapsPacket))]
[MemoryPackUnion(9, typeof(WriteNpcsPacket))]
[MemoryPackUnion(10, typeof(WriteItemsPacket))]
[MemoryPackUnion(11, typeof(WriteShopsPacket))]
[MemoryPackUnion(12, typeof(RequestClassesPacket))]
[MemoryPackUnion(13, typeof(RequestMapPacket))]
[MemoryPackUnion(14, typeof(RequestMapsPacket))]
[MemoryPackUnion(15, typeof(RequestNpcsPacket))]
[MemoryPackUnion(16, typeof(RequestItemsPacket))]
[MemoryPackUnion(17, typeof(RequestShopsPacket))]
[MemoryPackUnion(18, typeof(PartyInvitePacket))]
[MemoryPackUnion(19, typeof(PartyAcceptPacket))]
[MemoryPackUnion(20, typeof(PartyDeclinePacket))]
[MemoryPackUnion(21, typeof(PartyLeavePacket))]
[MemoryPackUnion(22, typeof(PlayerMovePacket))]
[MemoryPackUnion(23, typeof(PlayerAttackPacket))]
[MemoryPackUnion(24, typeof(AddPointPacket))]
[MemoryPackUnion(25, typeof(CollectItemPacket))]
[MemoryPackUnion(26, typeof(DropItemPacket))]
[MemoryPackUnion(27, typeof(InventoryChangePacket))]
[MemoryPackUnion(28, typeof(InventoryUsePacket))]
[MemoryPackUnion(29, typeof(EquipmentRemovePacket))]
[MemoryPackUnion(30, typeof(HotbarAddPacket))]
[MemoryPackUnion(31, typeof(HotbarChangePacket))]
[MemoryPackUnion(32, typeof(HotbarUsePacket))]
[MemoryPackUnion(33, typeof(ShopBuyPacket))]
[MemoryPackUnion(34, typeof(ShopSellPacket))]
[MemoryPackUnion(35, typeof(ShopClosePacket))]
[MemoryPackUnion(36, typeof(TradeInvitePacket))]
[MemoryPackUnion(37, typeof(TradeAcceptPacket))]
[MemoryPackUnion(38, typeof(TradeDeclinePacket))]
[MemoryPackUnion(39, typeof(TradeLeavePacket))]
[MemoryPackUnion(40, typeof(TradeOfferPacket))]
[MemoryPackUnion(41, typeof(TradeOfferStatePacket))]
public partial interface IClientPacket : IPacket;
