<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Networking">
    <PackageVersion Include="LiteNetLib" Version="2.1.4" />
  </ItemGroup>

  <ItemGroup Label="Security">
    <PackageVersion Include="BCrypt.Net-Next" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup Label="Database">
    <PackageVersion Include="linq2db" Version="6.4.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup Label="Serialization">
    <PackageVersion Include="MemoryPack" Version="1.21.4" />
  </ItemGroup>

  <ItemGroup Label="Host infrastructure">
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup Label="Logging">
    <PackageVersion Include="ZLogger" Version="2.5.10" />
  </ItemGroup>

  <ItemGroup Label="Client">
    <PackageVersion Include="Iguina" Version="1.1.5" />
    <PackageVersion Include="Iguina.Drivers.Sfml" Version="1.0.0" />
    <PackageVersion Include="SFML.Audio" Version="3.0.0" />
    <PackageVersion Include="SFML.Graphics" Version="3.0.0" />
    <PackageVersion Include="SFML.Window" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup Label="Editor">
    <PackageVersion Include="Avalonia" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Dock.Avalonia" Version="12.1.0.4" />
    <PackageVersion Include="Dock.Model.Avalonia" Version="12.1.0.2" />
    <PackageVersion Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageVersion Include="Nox.Avalonia" Version="1.1.1" />
    <PackageVersion Include="Nox.Avalonia.DataGrid" Version="1.1.1" />
    <PackageVersion Include="Nox.Avalonia.Dock" Version="1.1.1" />
    <PackageVersion Include="Nox.Avalonia.PropertyGrid" Version="1.1.1" />
    <PackageVersion Include="PanAndZoom" Version="12.0.0.1" />
    <PackageVersion Include="bodong.Avalonia.PropertyGrid" Version="12.0.4.1" />
  </ItemGroup>

  <ItemGroup Label="Tooling">
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>
</Project>