<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Title>CryBits.Server</Title>
    <Product>CryBits</Product>
    <AssemblyVersion>0.8.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>CryBits.Server</RootNamespace>
    <AssemblyName>CryBits.Server</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Server/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="ZLogger" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Host/CryBits.Host.csproj" />
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Protocol/CryBits.Protocol.csproj" />
    <ProjectReference Include="../CryBits.Transport/CryBits.Transport.csproj" />
  </ItemGroup>
</Project>