<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Title>Client</Title>
    <Product>CryBits.Client</Product>
    <AssemblyVersion>0.8.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>CryBits.Client</RootNamespace>
    <AssemblyName>CryBits.Client</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <StartupObject>CryBits.Client.Program</StartupObject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Client and Editors/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arch" Version="2.1.0" />
    <PackageReference Include="Arch.System" Version="1.1.0" />
    <PackageReference Include="LiteNetLib" Version="2.1.4" />
    <PackageReference Include="SFML.Audio" Version="3.0.0" />
    <PackageReference Include="SFML.Graphics" Version="3.0.0" />
    <PackageReference Include="SFML.Window" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Transport/CryBits.Transport.csproj" />
    <ProjectReference Include="../CryBits.Client.Framework/CryBits.Client.Framework.csproj" />
    <ProjectReference Include="../CryBits.Persistence/CryBits.Persistence.csproj" />
    <ProjectReference Include="../CryBits.Host/CryBits.Host.csproj" />
  </ItemGroup>
</Project>
