<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Client</Title>
    <Product>CryBits.Client</Product>
    <AssemblyVersion>0.8.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>CryBits.Client</RootNamespace>
    <AssemblyName>CryBits.Client</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Client and Editors/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Myra" />
    <PackageReference Include="MonoGame.Framework.Native" />
    <PackageReference Include="FontStashSharp.MonoGame" />
    <PackageReference Include="LiteNetLib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Protocol/CryBits.Protocol.csproj" />
    <ProjectReference Include="../CryBits.Transport/CryBits.Transport.csproj" />
    <ProjectReference Include="../CryBits.Client.Framework/CryBits.Client.Framework.csproj" />
    <ProjectReference Include="../CryBits.Persistence/CryBits.Persistence.csproj" />
    <ProjectReference Include="../CryBits.Simulation/CryBits.Simulation.csproj" />
  </ItemGroup>
</Project>
