<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>CryBits.Host</Title>
    <Product>CryBits</Product>
    <AssemblyVersion>0.8.0</AssemblyVersion>
    <RootNamespace>CryBits.Host</RootNamespace>
    <AssemblyName>CryBits.Host</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="LiteNetLib" Version="2.1.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CryBits.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Transport/CryBits.Transport.csproj" />
    <ProjectReference Include="../CryBits.Simulation/CryBits.Simulation.csproj" />
    <ProjectReference Include="../CryBits.Persistence/CryBits.Persistence.csproj" />
  </ItemGroup>
</Project>