<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CryBits.Client.Framework</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>../../Build/Client.Framework/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Myra" />
    <PackageReference Include="MonoGame.Framework.Native" />
    <PackageReference Include="FontStashSharp.MonoGame" />
    <PackageReference Include="MemoryPack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Protocol/CryBits.Protocol.csproj" />
    <ProjectReference Include="../CryBits.Transport/CryBits.Transport.csproj" />
    <ProjectReference Include="../CryBits.Persistence/CryBits.Persistence.csproj" />
  </ItemGroup>
</Project>
