using MemoryPack;

namespace CryBits.Transport.Packets.Server;

[MemoryPackable]
[MemoryPackUnion(0, typeof(CreateCharacterPacket))]
[MemoryPackUnion(1, typeof(CharactersPacket))]
[MemoryPackUnion(2, typeof(ConnectPacket))]
[MemoryPackUnion(3, typeof(AlertPacket))]
[MemoryPackUnion(4, typeof(MessagePacket))]
[MemoryPackUnion(5, typeof(CombatAttackPacket))]
[MemoryPackUnion(6, typeof(MapsPacket))]
[MemoryPackUnion(7, typeof(MapPacket))]
[MemoryPackUnion(8, typeof(JoinMapPacket))]
[MemoryPackUnion(9, typeof(MapRevisionPacket))]
[MemoryPackUnion(10, typeof(MapNpcsPacket))]
[MemoryPackUnion(11, typeof(MapNpcPacket))]
[MemoryPackUnion(12, typeof(MapNpcMovementPacket))]
[MemoryPackUnion(13, typeof(MapNpcDirectionPacket))]
[MemoryPackUnion(14, typeof(MapNpcVitalsPacket))]
[MemoryPackUnion(15, typeof(MapNpcDiedPacket))]
[MemoryPackUnion(16, typeof(MapItemsPacket))]
[MemoryPackUnion(17, typeof(PartyPacket))]
[MemoryPackUnion(18, typeof(PartyInvitationPacket))]
[MemoryPackUnion(19, typeof(JoinGamePacket))]
[MemoryPackUnion(20, typeof(PlayerDataPacket))]
[MemoryPackUnion(21, typeof(PlayerPositionPacket))]
[MemoryPackUnion(22, typeof(PlayerVitalsPacket))]
[MemoryPackUnion(23, typeof(PlayerLeavePacket))]
[MemoryPackUnion(24, typeof(PlayerMovePacket))]
[MemoryPackUnion(25, typeof(PlayerDirectionPacket))]
[MemoryPackUnion(26, typeof(PlayerExperiencePacket))]
[MemoryPackUnion(27, typeof(PlayerInventoryPacket))]
[MemoryPackUnion(28, typeof(PlayerEquipmentsPacket))]
[MemoryPackUnion(29, typeof(PlayerHotbarPacket))]
[MemoryPackUnion(30, typeof(ClassesPacket))]
[MemoryPackUnion(31, typeof(NpcsPacket))]
[MemoryPackUnion(32, typeof(ItemsPacket))]
[MemoryPackUnion(33, typeof(JoinPacket))]
[MemoryPackUnion(34, typeof(ShopsPacket))]
[MemoryPackUnion(35, typeof(ShopOpenPacket))]
[MemoryPackUnion(36, typeof(TradePacket))]
[MemoryPackUnion(37, typeof(TradeInvitationPacket))]
[MemoryPackUnion(38, typeof(TradeStatePacket))]
[MemoryPackUnion(39, typeof(TradeOfferPacket))]
public partial interface IServerPacket : IPacket;
