<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>CryBits.Persistence</RootNamespace>
    <AssemblyName>CryBits.Persistence</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Persistence/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
  </ItemGroup>

</Project>
