<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>CryBits.Protocol</RootNamespace>
    <AssemblyName>CryBits.Protocol</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Protocol/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
  </ItemGroup>
</Project>
