<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Title>CryBits.Editors</Title>
    <Product>CryBits</Product>
    <AssemblyVersion>0.8.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>CryBits.Editors</RootNamespace>
    <AssemblyName>CryBits.Editors</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Client and Editors/</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <StartupObject>CryBits.Editors.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Dock.Avalonia" />
    <PackageReference Include="Dock.Model.Avalonia" />
    <PackageReference Include="Iguina" />
    <PackageReference Include="Iguina.Drivers.Sfml" />
    <PackageReference Include="LiteNetLib" />
    <PackageReference Include="MessageBox.Avalonia" />
    <PackageReference Include="Nox.Avalonia" />
    <PackageReference Include="Nox.Avalonia.DataGrid" />
    <PackageReference Include="Nox.Avalonia.Dock" />
    <PackageReference Include="Nox.Avalonia.PropertyGrid" />
    <PackageReference Include="PanAndZoom" />
    <PackageReference Include="SFML.Audio" />
    <PackageReference Include="SFML.Graphics" />
    <PackageReference Include="bodong.Avalonia.PropertyGrid" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Protocol/CryBits.Protocol.csproj" />
    <ProjectReference Include="../CryBits.Transport/CryBits.Transport.csproj" />
    <ProjectReference Include="../CryBits.Client.Framework/CryBits.Client.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="AvaloniaUI/Assets/**" />
  </ItemGroup>
</Project>