<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Title>CryBits.Editors</Title>
    <Product>CryBits</Product>
    <AssemblyVersion>0.8.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>CryBits.Editors</RootNamespace>
    <AssemblyName>CryBits.Editors</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Client and Editors/</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <StartupObject>CryBits.Editors.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Semi.Avalonia.ColorPicker" Version="12.0.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="LiteNetLib" Version="2.1.4" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageReference Include="Semi.Avalonia" Version="12.0.3" />
    <PackageReference Include="Semi.Avalonia.DataGrid" Version="12.0.0" />
    <PackageReference Include="SFML.Audio" Version="3.0.0" />
    <PackageReference Include="SFML.Graphics" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Network/CryBits.Network.csproj" />
    <ProjectReference Include="../CryBits.Client.Framework/CryBits.Client.Framework.csproj" />
    <ProjectReference Include="../CryBits.Core/CryBits.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="AvaloniaUI/Assets/**" />
  </ItemGroup>

</Project>