<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>CryBits.Definitions</RootNamespace>
    <AssemblyName>CryBits.Definitions</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Definitions/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" />
  </ItemGroup>
</Project>
