<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Title>Client Launcher</Title>
    <Product>CryBits.Client.Launcher</Product>
    <AssemblyVersion>0.8.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>CryBits.Client.Launcher</RootNamespace>
    <AssemblyName>CryBits.Client.Launcher</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Client and Editors/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Iguina" />
    <PackageReference Include="Iguina.Drivers.Sfml" />
    <PackageReference Include="LiteNetLib" />
    <PackageReference Include="SFML.Audio" />
    <PackageReference Include="SFML.Graphics" />
    <PackageReference Include="SFML.Window" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Client/CryBits.Client.csproj" />
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Protocol/CryBits.Protocol.csproj" />
    <ProjectReference Include="../CryBits.Transport/CryBits.Transport.csproj" />
    <ProjectReference Include="../CryBits.Client.Framework/CryBits.Client.Framework.csproj" />
    <ProjectReference Include="../CryBits.Persistence/CryBits.Persistence.csproj" />
    <ProjectReference Include="../CryBits.Host/CryBits.Host.csproj" />
    <ProjectReference Include="../CryBits.Simulation/CryBits.Simulation.csproj" />
  </ItemGroup>
</Project>
