<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>CryBits.Transport</RootNamespace>
    <AssemblyName>CryBits.Transport</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Transport/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteNetLib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
  </ItemGroup>

</Project>
