<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>CryBits.Simulation</RootNamespace>
    <AssemblyName>CryBits.Simulation</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../Build/Simulation/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CryBits.Definitions/CryBits.Definitions.csproj" />
    <ProjectReference Include="../CryBits.Protocol/CryBits.Protocol.csproj" />
  </ItemGroup>

</Project>
